services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: my-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://my-kafka:29092,PLAINTEXT_HOST://my-kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  branch:
    depends_on: 
      - kafka
    image: jhyeono2/branch:v1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    # command: mvn spring-boot:run
    ports:
      - 8082:8082
    working_dir: /usr/src
    volumes:
      - ./branch:/usr/src
      - ./maven-repo:/root/.m2
      
  center:
    depends_on: 
      - kafka
    image: jhyeono2/center:v1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    command: mvn spring-boot:run
    ports:
      - 8083:8083
    working_dir: /usr/src
    volumes:
      - ./center:/usr/src
      - ./maven-repo:/root/.m2
  
  dashboard:
    depends_on: 
      - kafka
    image: jhyeono2/dashboard:v1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    command: mvn spring-boot:run
    ports:
      - 8084:8084
    working_dir: /usr/src
    volumes:
      - ./dashboard:/usr/src
      - ./maven-repo:/root/.m2
      
  host:
    depends_on: 
      - kafka
    image: jhyeono2/host:v1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    command: mvn spring-boot:run
    ports:
      - 8085:8085
    working_dir: /usr/src
    volumes:
      - ./host:/usr/src
      - ./maven-repo:/root/.m2

  sanction:
    depends_on: 
      - kafka
    image: jhyeono2/sanction:v1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    command: mvn spring-boot:run
    ports:
      - 8086:8086
    working_dir: /usr/src
    volumes:
      - ./sanction:/usr/src
      - ./maven-repo:/root/.m2

  swift:
    depends_on: 
      - kafka
    image: jhyeono2/swift:v1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    command: mvn spring-boot:run
    ports:
      - 8087:8087
    working_dir: /usr/src
    volumes:
      - ./swift:/usr/src
      - ./maven-repo:/root/.m2
      
