name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./branch/pom.xml
          mvn clean package -f ./center/pom.xml
          mvn clean package -f ./sanction/pom.xml
          mvn clean package -f ./host/pom.xml
          mvn clean package -f ./dashboard/pom.xml
          mvn clean package -f ./swift/pom.xml

      - name: Docker Build and push for Branch
        uses: docker/build-push-action@v4
        with:
          context: ./branch
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/branch:latest
            ghcr.io/${{ github.repository }}/branch:${{ github.ref_name }}
            
      - name: Docker Build and push for Center
        uses: docker/build-push-action@v4
        with:
          context: ./center
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/center:latest
            ghcr.io/${{ github.repository }}/center:${{ github.ref_name }}
            
      - name: Docker Build and push for Sanction
        uses: docker/build-push-action@v4
        with:
          context: ./sanction
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/sanction:latest
            ghcr.io/${{ github.repository }}/sanction:${{ github.ref_name }}
            
      - name: Docker Build and push for Host
        uses: docker/build-push-action@v4
        with:
          context: ./host
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/host:latest
            ghcr.io/${{ github.repository }}/host:${{ github.ref_name }}
            
      - name: Docker Build and push for Dashboard
        uses: docker/build-push-action@v4
        with:
          context: ./dashboard
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/dashboard:latest
            ghcr.io/${{ github.repository }}/dashboard:${{ github.ref_name }}
            
      - name: Docker Build and push for Swift
        uses: docker/build-push-action@v4
        with:
          context: ./swift
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/swift:latest
            ghcr.io/${{ github.repository }}/swift:${{ github.ref_name }}
            
