apiVersion: apps/v1
kind: Deployment
metadata:
  name: branch
  labels:
    app: branch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: branch
  template:
    metadata:
      labels:
        app: branch
    spec:
      containers:
        - name: branch
          image: "username/branch:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
