apiVersion: apps/v1
kind: Deployment
metadata:
  name: branch
  labels:
    app: branch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: branch
  template:
    metadata:
      labels:
        app: branch
      annotations:
        sidecar.istio.io/inject: "true" # Istio 사이드카 주입 활성화
    spec:
      containers:
        - name: branch
          image: "user15.azurecr.io/branch:v26"
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: "200m"  
          # readinessProbe:
          #   httpGet:
          #     path: '/actuator/health'
          #     port: 8082
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 2
          #   periodSeconds: 5
          #   failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8082
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
