server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: branch
          uri: http://localhost:8082
          predicates:
            - Path=/accepts/**, /undefined/**, 
        - id: center
          uri: http://localhost:0
          predicates:
            - Path=/reviews/**, 
        - id: sanction
          uri: http://localhost:0
          predicates:
            - Path=/sanctions/**, 
        - id: host
          uri: http://localhost:0
          predicates:
            - Path=/hosts/**, /undefined/**, 
        - id: dashboard
          uri: http://localhost:0
          predicates:
            - Path=/undefined/**, /undefined/**, 
        - id: swift
          uri: http://localhost:0
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: branch
          uri: http://branch:8080
          predicates:
            - Path=/accepts/**, /undefined/**, 
        - id: center
          uri: http://center:8080
          predicates:
            - Path=/reviews/**, 
        - id: sanction
          uri: http://sanction:8080
          predicates:
            - Path=/sanctions/**, 
        - id: host
          uri: http://host:8080
          predicates:
            - Path=/hosts/**, /undefined/**, 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=/undefined/**, /undefined/**, 
        - id: swift
          uri: http://swift:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
