server:
  port: 8080

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: branch
          uri: http://localhost:8082
          predicates:
            - Path=/accepts/**, /undefined/**, 
        - id: center
          uri: http://localhost:8083
          predicates:
            - Path=/reviews/**, 
        - id: dashboard
          uri: http://localhost:8084
          predicates:
            - Path=/dashboard/**, /undefined/**, 
        - id: host
          uri: http://localhost:8085
          predicates:
            - Path=/hosts/**, /undefined/**, 
        - id: sanction
          uri: http://localhost:8086
          predicates:
            - Path=/sanctions/**, 
        - id: swift
          uri: http://localhost:8087
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8088
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: branch
          uri: http://branch:8082
          predicates:
            - Path=/accepts/**, /undefined/**, 
        - id: center
          uri: http://center:8083
          predicates:
            - Path=/reviews/**, 
        - id: dashboard
          uri: http://dashboard:8084
          predicates:
            - Path=/dashboard/**, /undefined/**, 
        - id: host
          uri: http://host:8085
          predicates:
            - Path=/hosts/**, /undefined/**, 
        - id: sanction
          uri: http://sanction:8086
          predicates:
            - Path=/sanctions/**, 
        - id: swift
          uri: http://swift:8087
          predicates:
            - Path=/swift/**, 
        - id: frontend
          uri: http://frontend:8088
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
