apiVersion: apps/v1
kind: Deployment
metadata:
  name: center
  labels:
    app: center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: center
  template:
    metadata:
      labels:
        app: center
    spec:
      containers:
        - name: center
          image: "user15.azurecr.io/center:v2"
          ports:
            - containerPort: 8083
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8083
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8083
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
