apiVersion: apps/v1
kind: Deployment
metadata:
  name: sanction
  labels:
    app: sanction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sanction
  template:
    metadata:
      labels:
        app: sanction
    spec:
      containers:
        - name: sanction
          image: "user15.azurecr.io/sanction:v5"
          ports:
            - containerPort: 8086
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8086
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8086
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
