---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: branch
  labels:
    app: branch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: branch
  template:
    metadata:
      labels:
        app: branch
    spec:
      containers:
        - name: branch
          image: username/branch:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: center
  labels:
    app: center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: center
  template:
    metadata:
      labels:
        app: center
    spec:
      containers:
        - name: center
          image: username/center:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sanction
  labels:
    app: sanction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sanction
  template:
    metadata:
      labels:
        app: sanction
    spec:
      containers:
        - name: sanction
          image: username/sanction:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: host
  labels:
    app: host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: host
  template:
    metadata:
      labels:
        app: host
    spec:
      containers:
        - name: host
          image: username/host:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
  labels:
    app: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
        - name: dashboard
          image: username/dashboard:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: swift
  labels:
    app: swift
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swift
  template:
    metadata:
      labels:
        app: swift
    spec:
      containers:
        - name: swift
          image: username/swift:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: branch
  labels:
    app: branch
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: branch


---


apiVersion: v1
kind: Service
metadata:
  name: center
  labels:
    app: center
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: center


---


apiVersion: v1
kind: Service
metadata:
  name: sanction
  labels:
    app: sanction
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: sanction


---


apiVersion: v1
kind: Service
metadata:
  name: host
  labels:
    app: host
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: host


---


apiVersion: v1
kind: Service
metadata:
  name: dashboard
  labels:
    app: dashboard
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: dashboard


---


apiVersion: v1
kind: Service
metadata:
  name: swift
  labels:
    app: swift
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: swift

